function getAllBlogs(){
	return blogs = [
		{"tag": "【spring】", "title": "【spring】使用DeferredResult实现相应的异步生成返回值的功能", "path": "./blogs/2017-03-01/spring-DeferredResult .js"},
		{"tag": "【mysql】", "title": "【mysql】常用sql语句", "path": "./blogs/2017-05-01/mysql-sql.js"},
		{"tag": "【mysql】", "title": "【mysql】事务", "path": "./blogs/2017-05-01/mysql-transaction.js"},
		{"tag": "【mysql】", "title": "【mysql】触发器", "path": "./blogs/2017-05-01/mysql-trigger.js"},
		{"tag": "【mysql】", "title": "【mysql】函数与存储过程", "path": "./blogs/2017-05-01/mysql-z-function and procedure.js"},
		{"tag": "【mysql】", "title": "【mysql】根据json类型的列中的某一个key来查询", "path": "./blogs/2017-05-02/mysql-json query.js"},
		{"tag": "【mysql】", "title": "【mysql】通过递归来实现树查询", "path": "./blogs/2017-05-02/mysql-tree query.js"},
		{"tag": "【mysql】", "title": "【mysql】通过左右值编码来实现树查询", "path": "./blogs/2017-05-02/mysql-tree query2.js"},
		{"tag": "【mysql】", "title": "【mysql】幂等性", "path": "./blogs/2017-05-03/mysql-mi deng xing.js"},
		{"tag": "【mysql】", "title": "【mysql】乐观锁和悲观锁", "path": "./blogs/2017-05-03/mysql-Pessimistic Lock and Optimistic Lock.js"},
		{"tag": "【webpack3】", "title": "【webpack3】入门", "path": "./blogs/2018-01-01/webpack-quickstart.js"},
		{"tag": "【mock】", "title": "【mock】如何在react中使用mock来模拟fetch请求的返回数据", "path": "./blogs/2018-01-10/mock-react.js"},
		{"tag": "【java】", "title": "【java】JVM工作原理", "path": "./blogs/2018-06-01/jvm lifecycle.js"},
		{"tag": "【springboot】", "title": "【springboot】HelloWorld", "path": "./blogs/2018-07-07/springboot-helloworld.js"},
		{"tag": "【springboot】", "title": "【springboot】全局配置文件", "path": "./blogs/2018-07-08/springboot-gloable configuration file.js"},
		{"tag": "【springboot】", "title": "【springboot】配置类", "path": "./blogs/2018-07-09/springboot-configuration class.js"},
		{"tag": "【springboot】", "title": "【springboot】starter启动器", "path": "./blogs/2018-07-10/springboot-starter.js"},
		{"tag": "【springboot】", "title": "【springboot】日志系统", "path": "./blogs/2018-07-11/springboot-log.js"},
		{"tag": "【springboot】", "title": "【springboot】整合thymeleaf模板引擎", "path": "./blogs/2018-07-12/springboot-thymeleaf.js"},
		{"tag": "【springboot】", "title": "【springboot】整合MyBatis", "path": "./blogs/2018-07-13/springboot-mybatis.js"},
		{"tag": "【springboot】", "title": "【springboot】整合Redis", "path": "./blogs/2018-07-13/springboot-redis.js"},
		{"tag": "【springboot】", "title": "【springboot】异常处理", "path": "./blogs/2018-07-14/springboot-exception.js"},
		{"tag": "【springboot】", "title": "【springboot】任务", "path": "./blogs/2018-07-15/springboot-task.js"},
		{"tag": "【springboot】", "title": "【springboot】拦截器", "path": "./blogs/2018-07-16/springboot-interceptor.js"},
		{"tag": "【springboot】", "title": "【springboot】整合swagger", "path": "./blogs/2018-07-17/springboot-swagger.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】微服务架构", "path": "./blogs/2018-08-01/springcloud-microservice.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Eureka", "path": "./blogs/2018-08-02/springcloud-eureka.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】搭建一个微服务并将其注册进Eureka注册中心", "path": "./blogs/2018-08-03/springcloud-eureka client.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】搭建Eureka服务注册中心", "path": "./blogs/2018-08-03/springcloud-eureka server.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Eureka的自我保护机制", "path": "./blogs/2018-08-04/springcloud-eureka sefl protect.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Eureka的集群配置", "path": "./blogs/2018-08-04/springcloud-eureka server cluster.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Eureka比Zookeeper好在哪儿", "path": "./blogs/2018-08-04/springcloud-how are eureka better than zookeeper.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Eureka的服务发现", "path": "./blogs/2018-08-04/springcloud-service discovery.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Ribbon", "path": "./blogs/2018-08-05/springcloud-ribbon.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】分布式配置中心", "path": "./blogs/2018-08-06/springcloud-config.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Feign", "path": "./blogs/2018-08-06/springcloud-feign.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Hystrix", "path": "./blogs/2018-08-06/springcloud-Hystrix.js"},
		{"tag": "【微服务—springcloud】", "title": "【微服务—springcloud】Zuul", "path": "./blogs/2018-08-06/springcloud-Zuul.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】Devops核心要点及kubernetes架构概述", "path": "./blogs/2018-11-20/kubernetes-Devops core and the core architecture of kubernetes.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】使用kubeadm部署Kubernetes集群", "path": "./blogs/2018-11-22/kubernetes-deploy k8s cluster using kubeadm.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】搭建单节点k8s", "path": "./blogs/2018-11-22/kubernetes-deploy k8s cluster with single node.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】使用kubectl相关命令与Kubernetes集群进行交互", "path": "./blogs/2018-11-25/kubernetes-kubectl.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】kubernetes中的资源", "path": "./blogs/2018-11-26/kubernetes-resource.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】pod资源", "path": "./blogs/2018-11-27/kubernetes-pod resource.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】pod控制器资源", "path": "./blogs/2018-11-28/kubernetes-pod controller resource.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】service资源", "path": "./blogs/2018-12-01/kubernetes-service resource.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】Ingress和IngressController资源", "path": "./blogs/2018-12-02/kubernetes-ingress and ingressController resource.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】存储卷", "path": "./blogs/2018-12-04/kubernetes-volume.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】权限认证", "path": "./blogs/2018-12-07/kubernetes-authorization.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】dashboard", "path": "./blogs/2018-12-08/kubernetes-dashboard.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】网路插件", "path": "./blogs/2018-12-09/kubernetes-network-plugin.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】调度器", "path": "./blogs/2018-12-10/kubernetes-scheduler.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】容器资源需求、资源限制及HeapSter", "path": "./blogs/2018-12-11/kubernetes-resource-limit-and-HeapSter.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】资源指标API及自定义指标API", "path": "./blogs/2018-12-12/kubernetes-resourceApi-and-customResourceApi.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】helm", "path": "./blogs/2018-12-13/kubernetes-helm.js"},
		{"tag": "【kubernetes】", "title": "【kubernetes】基于Kubernetes的PaaS概述", "path": "./blogs/2018-12-14/kubernetes-pass platform based on kubernetes.js"},
		{"tag": "【微服务—kong】", "title": "【微服务—kong】kong是什么", "path": "./blogs/2019-01-02/kong-what is kong.js"},
		{"tag": "【微服务—kong】", "title": "【微服务—kong】配置kong", "path": "./blogs/2019-01-03/kong-configuration.js"},
		{"tag": "【微服务—kong】", "title": "【微服务—kong】反向代理", "path": "./blogs/2019-01-03/kong-proxy.js"},
		{"tag": "【微服务—kong】", "title": "【微服务—kong】负载均衡及健康检查", "path": "./blogs/2019-01-04/kong-loadbalance and healthcheck.js"},
		{"tag": "【微服务—kong】", "title": "【微服务—kong】kong集群", "path": "./blogs/2019-01-05/kong-cluster.js"},
		{"tag": "【微服务—kong】", "title": "【微服务—kong】自定义插件", "path": "./blogs/2019-01-05/kong-plugin.js"},
		{"tag": "【微服务—kong】", "title": "【微服务—kong】在使用kong时遇到的问题", "path": "./blogs/2019-01-06/kong-bugfix.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】客户端使用方式", "path": "./blogs/2019-02-05/redis client.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】常用命令", "path": "./blogs/2019-02-05/redis common cmd.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】简介及其数据类型", "path": "./blogs/2019-02-05/redis data type.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】管道", "path": "./blogs/2019-02-06/redis pipeline.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】发布/订阅", "path": "./blogs/2019-02-06/redis publish and subscript.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】事务和脚本", "path": "./blogs/2019-02-06/redis transaction and script.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】持久化", "path": "./blogs/2019-02-07/redis persistence.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】分布式锁", "path": "./blogs/2019-02-08/redis distributed lock.js"},
		{"tag": "【Redis-5.0】", "title": "【Redis-5.0】高可用", "path": "./blogs/2019-02-08/redis high avaliability.js"},
		{"tag": "【消息中间件—rabbitmq】", "title": "【消息中间件—rabbitmq】HelloWorld", "path": "./blogs/2019-03-01/rabbitmq-1helloworld.js"},
		{"tag": "【消息中间件—rabbitmq】", "title": "【消息中间件—rabbitmq】工作队列", "path": "./blogs/2019-03-01/rabbitmq-2workqueue.js"},
		{"tag": "【消息中间件—rabbitmq】", "title": "【消息中间件—rabbitmq】发布和订阅", "path": "./blogs/2019-03-01/rabbitmq-3publish-subscribe.js"},
		{"tag": "【消息中间件—rabbitmq】", "title": "【消息中间件—rabbitmq】路由选择", "path": "./blogs/2019-03-01/rabbitmq-4routing.js"},
		{"tag": "【消息中间件—rabbitmq】", "title": "【消息中间件—rabbitmq】主题", "path": "./blogs/2019-03-01/rabbitmq-5topic.js"},
		{"tag": "【消息中间件—rabbitmq】", "title": "【消息中间件—rabbitmq】RPC远程调用", "path": "./blogs/2019-03-01/rabbitmq-6rpc.js"},
		{"tag": "【微服务—分布式事务解决方案】", "title": "【微服务—分布式事务解决方案】基于XA协议的两阶段提交方案", "path": "./blogs/2019-04-01/distribute transaction1-xa.js"},
		{"tag": "【微服务—分布式事务解决方案】", "title": "【微服务—分布式事务解决方案】TCC方案", "path": "./blogs/2019-04-01/distribute transaction2 tcc.js"},
		{"tag": "【微服务—分布式事务解决方案】", "title": "【微服务—分布式事务解决方案】基于消息的最终一致性方案", "path": "./blogs/2019-04-02/distribute transaction-mq.js"},
		{"tag": "【微服务—分布式事务解决方案】", "title": "【微服务—分布式事务解决方案】基于网关及消息的最终一致性方案", "path": "./blogs/2019-04-03/distribute transaction-mq-apigateway.js"},
		{"tag": "【graphql】", "title": "【graphql】概述", "path": "./blogs/2019-04-20/graphql-started.js"},
		{"tag": "【设计模式】", "title": "【设计模式】设计模式的三个分类", "path": "./blogs/2019-06-01/design pattern catalog.js"},
		{"tag": "【设计模式】", "title": "【设计模式】工厂方法模式和抽象工厂模式", "path": "./blogs/2019-06-01/factory.js"},
		{"tag": "【设计模式】", "title": "【设计模式】观察者模式", "path": "./blogs/2019-06-01/observer.js"},
		{"tag": "【设计模式】", "title": "【设计模式】单例模式", "path": "./blogs/2019-06-01/singleton.js"},
		{"tag": "【设计模式】", "title": "【设计模式】适配器模式", "path": "./blogs/2019-06-02/adapter.js"},
		{"tag": "【设计模式】", "title": "【设计模式】装饰模式", "path": "./blogs/2019-06-02/decorator.js"},
		{"tag": "【设计模式】", "title": "【设计模式】代理模式", "path": "./blogs/2019-06-02/proxy.js"},
		{"tag": "【设计模式】", "title": "【设计模式】策略模式", "path": "./blogs/2019-06-02/strategy.js"},
		{"tag": "【设计模式】", "title": "【设计模式】建造者模式", "path": "./blogs/2019-06-03/builder.js"},
		{"tag": "【设计模式】", "title": "【设计模式】委派模式", "path": "./blogs/2019-06-03/delegate.js"},
		{"tag": "【设计模式】", "title": "【设计模式】模板方法模式", "path": "./blogs/2019-06-03/template.js"},
		{"tag": "【prometheus】", "title": "【prometheus】Prometheus的alert产生过程和AlertManager告警处理流程", "path": "./blogs/2019-07-08/alertmanager-alert-period.js"},
		{"tag": "【瞎几把想】", "title": "【瞎几把想】数据库表中同时存在id和code两个唯一字段的好处", "path": "./blogs/2019-07-26/code is useful.js"},
		{"tag": "【Vitess】", "title": "【Vitess】在k8s中使用chart部署vitess", "path": "./blogs/2019-07-31/deploy vitess in k8s using chart.js"},
		{"tag": "【Vitess】", "title": "【Vitess】在k8s中使用operator部署vitess", "path": "./blogs/2019-07-31/deploy vitess in k8s.js"},
		{"tag": "【Vitess】", "title": "【Vitess】通过http请求对vitess中的所有资源对象进行增删改查", "path": "./blogs/2019-07-31/vitess http operating.js"},
		{"tag": "【Vitess】", "title": "【Vitess】什么是vitess，为什么需要vitess", "path": "./blogs/2019-07-31/what is vitess,why vitess.js"},
		{"tag": "【Vitess】", "title": "【Vitess】vitess的架构及其核心概念", "path": "./blogs/2019-08-02/architecture and concepts.js"},
		{"tag": "【Vitess】", "title": "【Vitess】用户指南之备份和恢复数据", "path": "./blogs/2019-08-05/user guide - backing up and restoring data.js"},
		{"tag": "【Vitess】", "title": "【Vitess】用户指南之Reparenting", "path": "./blogs/2019-08-05/user guide - reparenting.js"},
		{"tag": "【Vitess】", "title": "【Vitess】用户指南之VTExplain", "path": "./blogs/2019-08-05/user guide - vtexplain.js"},
		{"tag": "【Vitess】", "title": "【Vitess】用户指南之VTTablet模型", "path": "./blogs/2019-08-05/user guide - vttablet modes.js"},
		{"tag": "【Vitess】", "title": "【Vitess】用户指南之Topology服务", "path": "./blogs/2019-08-06/user guide - topology service.js"},
		{"tag": "【Vitess】", "title": "【Vitess】数据传输安全模型", "path": "./blogs/2019-08-10/user guide - Transport Security Model.js"},
		{"tag": "【Vitess】", "title": "【Vitess】vitess中不支持的sql类型", "path": "./blogs/2019-08-12/unsupported sql in vitess.js"},
		{"tag": "【Vitess】", "title": "【Vitess】vitess相关操作的详细说明", "path": "./blogs/2019-08-13/detail operation in vitess.js"},
		{"tag": "【React Native】", "title": "【React Native】如何搭建ReactNative开发环境？", "path": "./blogs/2019-10-31/how to build react native develop environment.js"},
		{"tag": "【React Native】", "title": "【React Native】如何优化ReactNative代码的目录结构？", "path": "./blogs/2019-10-31/how to optimize the code file structure.js"},
		{"tag": "【React Native】", "title": "【React Native】如何设置App的名称以及启动页？", "path": "./blogs/2019-10-31/how to set app name and starup page.js"},
		{"tag": "【React Native】", "title": "【React Native】如何在ReactNative中高效的使用Form表单？", "path": "./blogs/2019-10-31/how to use form efficiently.js"},
		{"tag": "【React Native】", "title": "【React Native】如何使用ReactNative原生的Modal组件和原生的Image组件？", "path": "./blogs/2019-10-31/how to use Modal and Image.js"},
		{"tag": "【React Native】", "title": "【React Native】如何使用 react-navigation？", "path": "./blogs/2019-10-31/how to use react navigation.js"},
		{"tag": "【React Native】", "title": "【React Native】如何防止在当前组件销毁后还有setState的操作，防止内存泄漏", "path": "./blogs/2019-11-02/how to avoid setState after unmount.js"},
		{"tag": "【React Native】", "title": "【React Native】如何实现数字密码设置或校验组件？", "path": "./blogs/2019-11-02/how to implement digit keyboard.js"},
		{"tag": "【React Native】", "title": "【React Native】如何实现页面右侧字母搜索栏和自定义页头？", "path": "./blogs/2019-11-02/how to implement letter search bar and custom header.js"},
		{"tag": "【React Native】", "title": "【React Native】如何使用react-native-ok-gesture-password来实现手势密码组件？", "path": "./blogs/2019-11-02/how to use gesture-password.js"},
		{"tag": "【React Native】", "title": "【React Native】如何使用react-native-sqlite-storage来将数据保存到本地？", "path": "./blogs/2019-11-02/how to use sqlite.js"},
		{"tag": "【java并发编程】", "title": "【java并发编程】java原生的并发编程方式", "path": "./blogs/2019-11-03/concurrent programming in java.js"},
		{"tag": "【java并发编程】", "title": "【java并发编程】实现简单的线程池", "path": "./blogs/2019-11-09/cutom simple thread pool.js"},
		{"tag": "【java并发编程】", "title": "【java并发编程】Reactor响应式编程", "path": "./blogs/2019-11-15/reactor.js"},
		{"tag": "【分布式配置中心—Apollo】", "title": "【分布式配置中心—Apollo】基于 java 的分布式配置中心对比", "path": "./blogs/2019-11-17/distributed configuration center compare.js"},
		{"tag": "【分布式配置中心—Apollo】", "title": "【分布式配置中心—Apollo】是否需要刷新在应用启动时所用到的配置", "path": "./blogs/2019-11-17/if need refresh configuration witch used in startup.js"},
		{"tag": "【分布式配置中心—Apollo】", "title": "【分布式配置中心—Apollo】概述", "path": "./blogs/2019-11-23/apollo overview.js"},
		{"tag": "【分布式配置中心—Apollo】", "title": "【分布式配置中心—Apollo】架构设计及实现原理", "path": "./blogs/2019-11-23/architecture design.js"},
		{"tag": "【分布式配置中心—Apollo】", "title": "【分布式配置中心—Apollo】部署apollo服务端", "path": "./blogs/2019-11-23/deploy apollo server.js"},
		{"tag": "【分布式配置中心—Apollo】", "title": "【分布式配置中心—Apollo】动态修改应用配置的几种方式", "path": "./blogs/2019-11-23/how to change configuration automatically.js"},
		{"tag": "【分布式配置中心—Apollo】", "title": "【分布式配置中心—Apollo】Java客户端使用方式", "path": "./blogs/2019-11-23/usage of java client.js"},
		{"tag": "【spring】", "title": "【spring】Spring的两大特性： aop 和 ioc", "path": "./blogs/2020-01-07/AOP and IOC.js"},
		{"tag": "【spring】", "title": "【spring】Spring启动过程", "path": "./blogs/2020-01-08/spring startup process.js"},
		{"tag": "【java】", "title": "【java】Java注解", "path": "./blogs/2020-02-28/java annotation.js"},
		{"tag": "【spring】", "title": "【spring】使用Spring来加载工程下所有jar包下的指定资源", "path": "./blogs/2020-03-16/get all classpath resources.js"},
		{"tag": "【java并发编程】", "title": "【java并发编程】Stream流", "path": "./blogs/2020-03-16/stream.js"},
		{"tag": "【springboot】", "title": "【springboot】SpringBoot底层原理", "path": "./blogs/2020-03-30/springboot startup.js"},
		{"tag": "【springboot】", "title": "【springboot】如何向 SpringBoot 中添加自定义的配置源", "path": "./blogs/2020-04-02/how to add propertysource in springboot.js"}
	]
}